baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Bram Beekman | Boilerplate Bootstrap Vite'
primary: true
siteGroup: 4417a851-73ed-4397-aaec-e92d6a27dadc # Bram Beekman | Boilerplate Bootstrap Vite
sortOrder: 1
